(nil . ((projectile-project-name . "Microcelium Fake")
         (projectile-project-compilation-cmd . "./build.sh")
         (projectile-project-test-cmd . "./build.sh -t Test")
         (projectile-project-run-cmd . "")))
; (csharp-mode . ((eval . (progn (message "csharp properties")))))
; (fsharp-mode . ((eval . (progn (message "fsharp properties"))))))
;(projectile-globally-ignored-files . ("bin" "obj" "*.lock" "**/Debug" "**/Release"))
