# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  Release: 1
  VersionPrefix: 1.2.0
  VersionSuffix: $[counter(variables['VersionPrefix'], 0)]

steps:
- checkout: self
  persistCredentials: true
- task: UseDotNet@2
  inputs:
    useGlobalJson: true
- task: NuGetAuthenticate@0
  inputs:
    forceReinstallCredentialProvider: true
- bash: export Version="$(VersionPrefix).$(VersionSuffix)" && ./build.sh
- task: NuGetCommand@2
  inputs:
    command: 'push'
    packagesToPush: '$(Build.BinariesDirectory)/**/*.nupkg'
    publishVstsFeed: 'DataDx/DataDxNuget'
- bash: git tag $(Build.BuildNumber) && git push origin $(Build.BuildNumber)
  workingDirectory: $(Build.SourcesDirectory)