# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
- name: Release
  value: 1

steps:
- task: GetRevision@1
- task: NuGetAuthenticate@0
- bash: export BUILD_PATCHNUMBER=$(Revision) && ./build.sh
- task: NuGetCommand@2
  inputs:
    command: 'push'
    packagesToPush: '$(Build.BinariesDirectory)/**/*.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: 'a3336200-6a09-4f84-bc50-005bbda90364/a3b10c97-911e-4567-8b1e-4bb97c7701b4'