# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
- name: Release
  value: 1

steps:
- bash: ./build.sh
- task: NuGetAuthenticate@0
- task: NuGetCommand@2
  inputs:
    command: 'push'
    packagesToPush: '$(Build.BinariesDirectory)/**/*.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: '3b7f4a3f-fd2f-404e-8fe0-85ad6b6c950f/41c3678c-0c57-4e19-a2f9-7901be25c9b8'
    allowPackageConflicts: true
